"use client";
import Head from "next/head";
import Protected from "../hooks/useProtected";
import User from "../components/molecules/user";

export default function Home() {
  return (
    <>
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Protected>
        <User />
      </Protected>
    </>
  );
}
